# Generated by Django 6.0.3 on 2026-03-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAWAL", "Withdrawal"),
                    ("PAYMENT", "Payment"),
                    ("REFUND", "Refund"),
                    ("COMMISSION", "Commission"),
                    ("BONUS", "Bonus"),
                    ("SUBSCRIPTION", "Subscription"),
                ],
                max_length=20,
            ),
        ),
    ]
