# Generated by Django 6.0.3 on 2026-03-18 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Audiobook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("narrator", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("FICTION", "Fiction"),
                            ("NON_FICTION", "Non-Fiction"),
                            ("BIOGRAPHY", "Biography"),
                            ("BUSINESS", "Business"),
                            ("SELF_HELP", "Self-Help"),
                            ("ROMANCE", "Romance"),
                            ("THRILLER", "Thriller"),
                            ("SCIFI", "Science Fiction"),
                            ("FANTASY", "Fantasy"),
                            ("HISTORY", "History"),
                            ("EDUCATION", "Education"),
                            ("CHILDREN", "Children"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("EN", "English"),
                            ("FR", "French"),
                            ("AR", "Arabic"),
                            ("SW", "Swahili"),
                            ("HA", "Hausa"),
                            ("YO", "Yoruba"),
                            ("IG", "Igbo"),
                            ("ZH", "Chinese"),
                            ("ES", "Spanish"),
                            ("PT", "Portuguese"),
                        ],
                        default="EN",
                        max_length=5,
                    ),
                ),
                ("duration_minutes", models.IntegerField()),
                ("file_size", models.BigIntegerField(help_text="Size in bytes")),
                ("cover_image", models.URLField(blank=True, max_length=500)),
                ("audio_file_url", models.URLField(max_length=500)),
                ("sample_audio_url", models.URLField(blank=True, max_length=500)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_free", models.BooleanField(default=False)),
                ("is_premium", models.BooleanField(default=False)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("published_date", models.DateField()),
                ("isbn", models.CharField(blank=True, max_length=20)),
                ("total_plays", models.IntegerField(default=0)),
                ("total_downloads", models.IntegerField(default=0)),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("rating_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AudiobookProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_position",
                    models.IntegerField(
                        default=0, help_text="Current position in seconds"
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("last_played_at", models.DateTimeField(auto_now=True)),
                (
                    "audiobook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="audiobooks.audiobook",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audiobook_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "audiobook")},
            },
        ),
        migrations.CreateModel(
            name="AudiobookRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("review", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "audiobook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="audiobooks.audiobook",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audiobook_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "audiobook")},
            },
        ),
    ]
