# Generated by Django 6.0.3 on 2026-03-18 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("isbn", models.CharField(blank=True, max_length=20)),
                ("publisher", models.CharField(blank=True, max_length=255)),
                ("published_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("FICTION", "Fiction"),
                            ("NON_FICTION", "Non-Fiction"),
                            ("BIOGRAPHY", "Biography"),
                            ("BUSINESS", "Business"),
                            ("SELF_HELP", "Self-Help"),
                            ("ROMANCE", "Romance"),
                            ("THRILLER", "Thriller"),
                            ("SCIFI", "Science Fiction"),
                            ("FANTASY", "Fantasy"),
                            ("HISTORY", "History"),
                            ("EDUCATION", "Education"),
                            ("CHILDREN", "Children"),
                            ("ACADEMIC", "Academic"),
                            ("RELIGIOUS", "Religious"),
                            ("COMICS", "Comics"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("EN", "English"),
                            ("FR", "French"),
                            ("AR", "Arabic"),
                            ("SW", "Swahili"),
                            ("HA", "Hausa"),
                            ("YO", "Yoruba"),
                            ("IG", "Igbo"),
                            ("ZH", "Chinese"),
                            ("ES", "Spanish"),
                            ("PT", "Portuguese"),
                        ],
                        default="EN",
                        max_length=5,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("LIKE_NEW", "Like New"),
                            ("VERY_GOOD", "Very Good"),
                            ("GOOD", "Good"),
                            ("ACCEPTABLE", "Acceptable"),
                            ("POOR", "Poor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pages", models.IntegerField(blank=True, null=True)),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, help_text="Format: L x W x H in cm", max_length=100
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in grams",
                        max_digits=6,
                        null=True,
                    ),
                ),
                ("cover_image", models.URLField(blank=True, max_length=500)),
                (
                    "additional_images",
                    models.JSONField(
                        blank=True, default=list, help_text="List of image URLs"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_negotiable", models.BooleanField(default=False)),
                ("seller_location", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("SOLD", "Sold"),
                            ("RESERVED", "Reserved"),
                            ("PENDING", "Pending"),
                            ("REMOVED", "Removed"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("shipping_available", models.BooleanField(default=True)),
                (
                    "shipping_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("pickup_available", models.BooleanField(default=True)),
                ("view_count", models.IntegerField(default=0)),
                ("favorite_count", models.IntegerField(default=0)),
                ("inquiry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books_for_sale",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("seller_response", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ANSWERED", "Answered"),
                            ("CLOSED", "Closed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookFavorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "book")},
            },
        ),
        migrations.CreateModel(
            name="BookRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("review", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="books.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "book")},
            },
        ),
    ]
