#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
if [ ! -d "$DIR/venv" ]; then
    echo "Erreur: Le dossier venv est introuvable."
    exit 1
fi
"$DIR/venv/bin/python" "$DIR/manage.py" "$@"
